### Регистрация
POST http://127.0.0.1:8000/api_v1/auth/users/
Content-Type: application/json

{
  "email": "tets2@test.ru",
  "username": "djoser2",
  "password": "1A2b3c4d5E6f7G",
  "first_name": "Имя1"

}

### авторизуемся и получаем токен
POST http://127.0.0.1:8000/api_v1/auth/token/login/
Content-Type: application/json

{
  "username": "djoser2",
  "password": "1A2b3c4d5E6f7G"
}

### Информация о пользователе
GET http://127.0.0.1:8000/api_v1/auth/users/me/
Authorization: Token 26d1168537ea6017048b4851c9d1c7a2f97040c2

### Обновление Информация о пользователе
PUT http://127.0.0.1:8000/api_v1/auth/users/me/
Authorization: Token 2f122a9ba9135a5959333e61ddf388c4a7dcac0f
Content-Type: application/json

{
  "email": "tetst@test.ru",
  "username": "djoser231",
  "password": "1A2b3c4d5E6f7G",
  "first_name": "Имя"
}

### Выход
POST http://127.0.0.1:8000/api_v1/auth/token/logout/
Authorization: Token 952eaffc7e0dfba23a891bc845b59069c70cd7ba



### Просмотр доп. профиля
GET http://127.0.0.1:8000/api_v1/profile/
Authorization: Token 952eaffc7e0dfba23a891bc845b59069c70cd7ba

### Просмотр доп. профилей
GET http://127.0.0.1:8000/api_v1/profile/3/
Authorization: Token 952eaffc7e0dfba23a891bc845b59069c70cd7ba

### Обновление доп. профиля
PUT http://127.0.0.1:8000/api_v1/profile/3/
Authorization: Token 952eaffc7e0dfba23a891bc845b59069c70cd7ba
Content-Type: application/json

{
  "date_of_birth": "2022-04-07"
}






### Список постов
GET http://127.0.0.1:8000/api_v1/posts/
#Authorization: Token eb284d163d18dc1e8ba8d715987495fcc7635346
Authorization: Token 26d1168537ea6017048b4851c9d1c7a2f97040c2

### Создание поста
POST http://127.0.0.1:8000/api_v1/posts/
Content-Type: application/json
#Authorization: Token eb284d163d18dc1e8ba8d715987495fcc7635346
Authorization: Token 26d1168537ea6017048b4851c9d1c7a2f97040c2

{
  "title": "Post3",
  "description": "Description3",
  "price": 1500
}

### Удаление поста
DELETE http://127.0.0.1:8000/api_v1/posts/4/
Authorization: Token eb284d163d18dc1e8ba8d715987495fcc7635346
#Authorization: Token 3f1c6cc8d27588f7d92582d434c3a5153d825621

### Информация о посте
GET http://127.0.0.1:8000/api_v1/posts/3/
#Authorization: Token eb284d163d18dc1e8ba8d715987495fcc7635346
Authorization: Token 3f1c6cc8d27588f7d92582d434c3a5153d825621

### Обновление поста
PUT http://127.0.0.1:8000/api_v1/posts/3/
Authorization: Token 3f1c6cc8d27588f7d92582d434c3a5153d825621
Content-Type: application/json

{
  "title": "Post11",
  "description": "Description11"
}





### Список комментариев
GET http://127.0.0.1:8000/api_v1/comment/
Authorization: Token 26d1168537ea6017048b4851c9d1c7a2f97040c2

### Создание комментариев
POST http://127.0.0.1:8000/api_v1/comment/
Content-Type: application/json
Authorization: Token 26d1168537ea6017048b4851c9d1c7a2f97040c2

{
  "post": 5,
  "description": "Description text2"
}

### Удаление комментариея
DELETE http://127.0.0.1:8000/api_v1/comment/21/
Authorization: Token 26d1168537ea6017048b4851c9d1c7a2f97040c2

### Информация о комментарии
GET http://127.0.0.1:8000/api_v1/comment/21/
Authorization: Token 26d1168537ea6017048b4851c9d1c7a2f97040c2

### Обновление комментариея !!!Обновлять без указания поста
PUT http://127.0.0.1:8000/api_v1/comment/21/
Authorization: Token 26d1168537ea6017048b4851c9d1c7a2f97040c2
Content-Type: application/json

{
  "post": 5,
  "description": "Description11__"
}