# Generated by Django 3.2.12 on 2022-04-03 13:25

import backend.get_photo
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('limited', 'Ограниченный'), ('simple', 'Обычный'), ('representative', 'Представитель Магазина')], default='simple', max_length=25, verbose_name='Тип пользователя')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('date_of_birth', models.DateTimeField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to=backend.get_photo.get_upload_to_profile)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
