# Generated by Django 3.2.12 on 2022-04-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
